### ISSUE TITLE
Version 0.5.0 [add useful features]

### ISSUE THREAD

**Issue by koxudaxi** [koxudaxi/pydantic-pycharm-plugin#149]
Version 0.4 will support useful features.

## TODO

- [x] freeze a list of features 
- [x] implement features

## Features

- [x] Jump to pydantic official document from code #141
- [x] Insert Field by Quick Fix enhancement #139
