### ISSUE TITLE
Publish the plugin on Jetbrains repository

### ISSUE THREAD

**Issue by koxudaxi** [koxudaxi/pydantic-pycharm-plugin#25]
## Detail
We want to publish the plugin on Jetbrains repository

## TODO
- [x] add documents in the plugin.
- [x] upload the plugin to apply it.
- [x] create the plugin page.
- [x] publish the plugin by CI

## Plugin Page
https://plugins.jetbrains.com/plugin/12861-pydantic

## Screen Shots
<img width="719" alt="ss2019-08-13 1 38 21" src="https://user-images.githubusercontent.com/630670/62881613-24ea5c80-bd6b-11e9-9609-eade7739901c.png">

**Comment by samuelcolvin** [comment]
I would thoroughly recommend performing the upload processing in CI, slightly more work at the beginning but a massive headache removed later on.

**Comment by samuelcolvin** [comment]
ha, you added the same thing.

**Comment by koxudaxi** [comment]
I checked how to upload a plugin on CI.
I think I can use the same way in the repository.
https://github.com/KronicDeth/intellij-elixir/blob/f9dd6b5bad850bf61184941555cc6591c2ef2ce6/.travis.yml#L262

**Comment by koxudaxi** [comment]
@samuelcolvin 
Thank you for your advice.
I agree.
